import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";

export type ContentRecord = { id: string; contentAccountId: string | null; conversationId: string; sourceMessageId: string; title: string; bodyMarkdown: string; status: string; selectedCoverAssetId: string | null; notes: string | null; createdAt: number; updatedAt: number };
export type ContentAccount = { id: string; code: string; name: string; description: string | null; notes: string | null; defaultRuntimeConnectionId: string | null; defaultProfileId: string | null; enabled: boolean; createdAt: number; updatedAt: number };
export type ContentReview = { id: string; contentRecordId: string; requestMessageId: string; responseMessageId: string | null; score: number | null; resultMarkdown: string | null; status: string; createdAt: number };

export function titleFromMarkdown(markdown: string): string {
  const heading = markdown.match(/^#{1,2}\s+(.+)$/m)?.[1]?.trim();
  return (heading || markdown.replace(/[#*_`>\n]/g, " ").replace(/\s+/g, " ").trim().slice(0, 60) || "未命名内容").slice(0, 120);
}

export function createContentService(sqlite: Database.Database) {
  const mapContent = (row: Record<string, unknown>): ContentRecord => ({ id: String(row.id), contentAccountId: row.contentAccountId as string | null, conversationId: String(row.conversationId), sourceMessageId: String(row.sourceMessageId), title: String(row.title), bodyMarkdown: String(row.bodyMarkdown), status: String(row.status), selectedCoverAssetId: row.selectedCoverAssetId as string | null, notes: row.notes as string | null, createdAt: Number(row.createdAt), updatedAt: Number(row.updatedAt) });
  return {
    saveFromMessage(input: { messageId: string; operatorId: string; contentAccountId?: string | null }): ContentRecord {
      const message = sqlite.prepare(`SELECT messages.id, messages.conversation_id as conversationId, messages.content_text as contentText, messages.role, conversations.content_account_id as contentAccountId FROM messages INNER JOIN conversations ON conversations.id = messages.conversation_id WHERE messages.id = ? AND conversations.owner_operator_id = ?`).get(input.messageId, input.operatorId) as { id: string; conversationId: string; contentText: string; role: string; contentAccountId: string | null } | undefined;
      if (!message || message.role !== "assistant") throw new Error("Only completed assistant messages can be saved as content");
      const existing = sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records WHERE source_message_id = ? AND created_by_operator_id = ? ORDER BY created_at LIMIT 1`).get(message.id, input.operatorId) as Record<string, unknown> | undefined;
      if (existing) return mapContent(existing);
      const now = Date.now(); const id = randomUUID(); const title = titleFromMarkdown(message.contentText);
      sqlite.prepare(`INSERT INTO content_records (id, content_account_id, conversation_id, source_message_id, title, body_markdown, status, created_by_operator_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'draft', ?, ?, ?)`)
        .run(id, input.contentAccountId ?? message.contentAccountId, message.conversationId, message.id, title, message.contentText, input.operatorId, now, now);
      return mapContent(sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records WHERE id = ?`).get(id) as Record<string, unknown>);
    },
    list(): ContentRecord[] { return sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records ORDER BY updated_at DESC`).all().map((row) => mapContent(row as Record<string, unknown>)); },
    listOwned(operatorId: string): ContentRecord[] { return sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records WHERE created_by_operator_id = ? ORDER BY updated_at DESC`).all(operatorId).map((row) => mapContent(row as Record<string, unknown>)); },
    get(id: string): ContentRecord | undefined { const row = sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records WHERE id = ?`).get(id) as Record<string, unknown> | undefined; return row ? mapContent(row) : undefined; },
    getOwned(id: string, operatorId: string): ContentRecord | undefined { const row = sqlite.prepare(`SELECT id, content_account_id as contentAccountId, conversation_id as conversationId, source_message_id as sourceMessageId, title, body_markdown as bodyMarkdown, status, selected_cover_asset_id as selectedCoverAssetId, notes, created_at as createdAt, updated_at as updatedAt FROM content_records WHERE id = ? AND created_by_operator_id = ?`).get(id, operatorId) as Record<string, unknown> | undefined; return row ? mapContent(row) : undefined; },
    listReviews(contentRecordId: string): ContentReview[] { return sqlite.prepare(`SELECT id, content_record_id as contentRecordId, request_message_id as requestMessageId, response_message_id as responseMessageId, score, result_markdown as resultMarkdown, status, created_at as createdAt FROM content_reviews WHERE content_record_id = ? ORDER BY created_at DESC`).all(contentRecordId) as ContentReview[]; },
    update(id: string, input: { title?: string; status?: string; notes?: string; bodyMarkdown?: string }): ContentRecord | undefined { const current = this.get(id); if (!current) return undefined; sqlite.prepare(`UPDATE content_records SET title = ?, status = ?, notes = ?, body_markdown = ?, updated_at = ? WHERE id = ?`).run(input.title?.trim() || current.title, input.status ?? current.status, input.notes ?? current.notes, input.bodyMarkdown ?? current.bodyMarkdown, Date.now(), id); return this.get(id); },
    updateOwned(id: string, operatorId: string, input: { title?: string; status?: string; notes?: string; bodyMarkdown?: string }): ContentRecord | undefined { const current = this.getOwned(id, operatorId); if (!current) return undefined; sqlite.prepare(`UPDATE content_records SET title = ?, status = ?, notes = ?, body_markdown = ?, updated_at = ? WHERE id = ? AND created_by_operator_id = ?`).run(input.title?.trim() || current.title, input.status ?? current.status, input.notes ?? current.notes, input.bodyMarkdown ?? current.bodyMarkdown, Date.now(), id, operatorId); return this.getOwned(id, operatorId); },
    selectCover(contentId: string, assetId: string): ContentRecord | undefined { const asset = sqlite.prepare(`SELECT id FROM assets WHERE id = ? AND content_record_id = ? AND asset_type = 'image'`).get(assetId, contentId); if (!asset) throw new Error("Cover must be an image asset attached to this content"); sqlite.prepare(`UPDATE content_records SET selected_cover_asset_id = ?, updated_at = ? WHERE id = ?`).run(assetId, Date.now(), contentId); return this.get(contentId); },
    listAccounts(): ContentAccount[] { return sqlite.prepare(`SELECT id, code, name, description, notes, default_runtime_connection_id as defaultRuntimeConnectionId, default_profile_id as defaultProfileId, enabled, created_at as createdAt, updated_at as updatedAt FROM content_accounts WHERE enabled = 1 ORDER BY code`).all() as ContentAccount[]; },
    createAccount(input: { code: string; name: string; description?: string; notes?: string; defaultRuntimeConnectionId?: string }): ContentAccount { const now = Date.now(); const id = randomUUID(); sqlite.prepare(`INSERT INTO content_accounts (id, code, name, description, notes, default_runtime_connection_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(id, input.code, input.name, input.description ?? null, input.notes ?? null, input.defaultRuntimeConnectionId ?? null, now, now); return sqlite.prepare(`SELECT id, code, name, description, notes, default_runtime_connection_id as defaultRuntimeConnectionId, default_profile_id as defaultProfileId, enabled, created_at as createdAt, updated_at as updatedAt FROM content_accounts WHERE id = ?`).get(id) as ContentAccount; },
    updateAccount(id: string, input: { name?: string; description?: string | null; notes?: string | null; defaultRuntimeConnectionId?: string | null; enabled?: boolean }): ContentAccount | undefined { const current = sqlite.prepare(`SELECT id, code, name, description, notes, default_runtime_connection_id as defaultRuntimeConnectionId, default_profile_id as defaultProfileId, enabled, created_at as createdAt, updated_at as updatedAt FROM content_accounts WHERE id = ?`).get(id) as ContentAccount | undefined; if (!current) return undefined; sqlite.prepare(`UPDATE content_accounts SET name = ?, description = ?, notes = ?, default_runtime_connection_id = ?, enabled = ?, updated_at = ? WHERE id = ?`).run(input.name?.trim() || current.name, input.description === undefined ? current.description : input.description, input.notes === undefined ? current.notes : input.notes, input.defaultRuntimeConnectionId === undefined ? current.defaultRuntimeConnectionId : input.defaultRuntimeConnectionId, input.enabled === undefined ? (current.enabled ? 1 : 0) : (input.enabled ? 1 : 0), Date.now(), id); return sqlite.prepare(`SELECT id, code, name, description, notes, default_runtime_connection_id as defaultRuntimeConnectionId, default_profile_id as defaultProfileId, enabled, created_at as createdAt, updated_at as updatedAt FROM content_accounts WHERE id = ?`).get(id) as ContentAccount; },
  };
}
