import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { createDatabase } from "@/infrastructure/db/client";
import { getCurrentOperatorId } from "@/modules/auth/current-operator";
import { createConversationService } from "@/modules/conversations/service";
import { getRuntimeConnectorForConnection } from "@/runtime/registry";
import { config } from "@/infrastructure/config/env";
import { decryptCredential } from "@/infrastructure/security/credentials";

export const runtime = "nodejs";
const schema = z.object({ conversationId: z.string().uuid(), name: z.string().trim().min(1).max(120), schedule: z.string().trim().min(1).max(160), prompt: z.string().trim().min(1).max(4000) });

export async function GET() { const operatorId = await getCurrentOperatorId(); if (!operatorId) return NextResponse.json({ message: "未登录" }, { status: 401 }); const { sqlite } = createDatabase(); try { return NextResponse.json(sqlite.prepare("SELECT id, conversation_id as conversationId, external_job_id as externalJobId, name, schedule, status, last_delivered_at as lastDeliveredAt, created_at as createdAt FROM runtime_jobs WHERE owner_operator_id = ? ORDER BY created_at DESC").all(operatorId)); } finally { sqlite.close(); } }
export async function POST(request: Request) { const operatorId = await getCurrentOperatorId(); if (!operatorId) return NextResponse.json({ message: "未登录" }, { status: 401 }); const body = schema.safeParse(await request.json().catch(() => null)); if (!body.success) return NextResponse.json({ message: "提醒参数不正确" }, { status: 400 }); const { sqlite } = createDatabase(); try { const conversation = createConversationService(sqlite, (id) => getRuntimeConnectorForConnection(sqlite, id)).get(body.data.conversationId, operatorId); if (!conversation) return NextResponse.json({ message: "会话不存在或无权创建提醒" }, { status: 403 }); const row = sqlite.prepare("SELECT base_url as baseUrl, credential_ciphertext as credentialCiphertext, config_json as configJson FROM runtime_connections WHERE id = ? AND type = 'hermes' AND enabled = 1").get(conversation.runtimeConnectionId) as { baseUrl: string; credentialCiphertext: string | null; configJson: string } | undefined; if (!row) return NextResponse.json({ message: "当前 Agent 不支持 Hermes Jobs API" }, { status: 400 }); let apiKey = row.credentialCiphertext ? decryptCredential(row.credentialCiphertext) : undefined; try { const envKey = (JSON.parse(row.configJson) as { apiKeyEnv?: string }).apiKeyEnv; apiKey ||= envKey ? process.env[envKey] : config.hermesApiKey; } catch { apiKey ||= config.hermesApiKey; }
    const response = await fetch(`${row.baseUrl.replace(/\/$/, "")}/api/jobs`, { method: "POST", headers: { "Content-Type": "application/json", ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}) }, body: JSON.stringify({ name: body.data.name, schedule: body.data.schedule, prompt: body.data.prompt, deliver: "local" }) }); const payload = await response.json().catch(() => ({})) as Record<string, unknown>; const externalJobId = typeof payload.id === "string" ? payload.id : typeof payload.job_id === "string" ? payload.job_id : typeof (payload.job as { id?: unknown } | undefined)?.id === "string" ? (payload.job as { id: string }).id : undefined; if (!response.ok || !externalJobId) return NextResponse.json({ message: typeof payload.error === "string" ? payload.error : "Hermes 未返回任务 ID" }, { status: 502 }); const now = Date.now(); const id = randomUUID(); sqlite.prepare("INSERT INTO runtime_jobs (id, runtime_connection_id, conversation_id, owner_operator_id, external_job_id, name, schedule, prompt, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, conversation.runtimeConnectionId, conversation.id, operatorId, externalJobId, body.data.name, body.data.schedule, body.data.prompt, now, now); return NextResponse.json({ id, externalJobId, status: "active" }, { status: 201 });
  } finally { sqlite.close(); } }
