"use client";

import { type FormEvent, useEffect, useEffectEvent, useState } from "react";
import { Archive, Bot, CheckCircle2, Circle, Database, HardDrive, Plus, RefreshCw, Server, ServerCog, UsersRound } from "lucide-react";
import { ConfirmDialog } from "@/shared/components/confirm-dialog";
import { useToast } from "@/shared/components/toast-provider";
import { useLocale } from "@/shared/i18n/locale-provider";

type Capabilities = { streaming: boolean; sessions: boolean; toolEvents: boolean; cancellation: boolean; attachments?: boolean };
type Health = { status: string; database?: string; storage?: string; security?: { dedicatedCredentialsKey: boolean; warning?: string }; runtime?: { status: string; message?: string; type?: string; capabilities?: Capabilities } };
type AgentHost = { id: string; name: string; address: string; description: string | null; enabled: boolean; agentCount: number };
type AgentInstance = { id: string; name: string; type: string; baseUrl: string; workspaceLabel: string; profileName: string; hostId: string | null; hostName: string | null; sharingMode: "shared" | "dedicated"; credentialMode: string; attachmentSupport: "files" | "images_only"; enabled: boolean };
type AgentHealth = { status: string; message?: string; capabilities?: Capabilities };
type AuditLog = { id: string; action: string; targetType: string; targetId: string | null; detailJson: string; operatorName: string | null; createdAt: number };
type DiscoveredAgent = { baseUrl: string; port: number; profiles: { id: string; name: string }[] };
type LocalProfile = { profileName: string; baseUrl: string | null; status: "healthy" | "offline" | "incomplete"; modelName: string | null; registered: boolean; hasApiKey: boolean };
type MemberAccessSummary = { activeMembers: number; membersWithChatAccess: number; membersWithoutChatAccess: number };
type StorageSettings = { dataDir: string; databasePath: string; storageConfigPath: string; restartRequired: boolean };
type SettingsTab = "overview" | "storage" | "setup" | "agents" | "audit";

export default function SettingsPage() {
  const [health, setHealth] = useState<Health>();
  const [hosts, setHosts] = useState<AgentHost[]>([]);
  const [agents, setAgents] = useState<AgentInstance[]>([]);
  const [isAdmin, setIsAdmin] = useState(false);
  const [agentHealth, setAgentHealth] = useState<Record<string, AgentHealth>>({});
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [rotatingAgentId, setRotatingAgentId] = useState<string | null>(null);
  const [discovered, setDiscovered] = useState<DiscoveredAgent[]>([]);
  const [localProfiles, setLocalProfiles] = useState<LocalProfile[]>([]);
  const [memberAccess, setMemberAccess] = useState<MemberAccessSummary>();
  const [storageSettings, setStorageSettings] = useState<StorageSettings>();
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [pendingHostDisable, setPendingHostDisable] = useState<AgentHost | null>(null);
  const [activeTab, setActiveTab] = useState<SettingsTab>("overview");
  const { notify } = useToast();
  const { locale } = useLocale();
  const l = (zh: string, en: string) => locale === "zh-CN" ? zh : en;
  const report = (text: string, tone: "success" | "error" | "info" = "info") => { setMessage(text); notify(text, tone); };

  async function load() {
    const [healthResponse, authorizedResponse, allResponse, hostsResponse, auditResponse] = await Promise.all([fetch("/api/health"), fetch("/api/agents"), fetch("/api/agent-instances"), fetch("/api/agent-hosts"), fetch("/api/audit-logs?limit=30")]);
    setHealth(await healthResponse.json());
    const authorized = authorizedResponse.ok ? await authorizedResponse.json() as AgentInstance[] : [];
    const admin = allResponse.ok; const visible = admin ? await allResponse.json() as AgentInstance[] : authorized;
    setIsAdmin(admin); setAgents(visible); setHosts(hostsResponse.ok ? await hostsResponse.json() : []); setAuditLogs(auditResponse.ok ? await auditResponse.json() : []);
    if (admin) {
      const [localResponse, accessResponse, storageResponse] = await Promise.all([fetch("/api/agent-hosts/local-discovery"), fetch("/api/members/access-summary"), fetch("/api/settings/storage")]);
      if (localResponse.ok) setLocalProfiles(await localResponse.json());
      if (accessResponse.ok) setMemberAccess(await accessResponse.json());
      if (storageResponse.ok) setStorageSettings(await storageResponse.json());
    }
    const checks = await Promise.all(visible.filter((agent) => agent.enabled).map(async (agent) => { const response = await fetch(`/api/agents/${agent.id}/health`); return [agent.id, response.ok ? await response.json() : { status: "offline", message: l("健康检查失败", "Health check failed") }] as const; }));
    setAgentHealth(Object.fromEntries(checks));
  }
  const loadSettings = useEffectEvent(() => { void load(); });
  useEffect(() => { const timer = window.setTimeout(loadSettings, 0); return () => window.clearTimeout(timer); }, []);

  async function backup() { setBusy(true); setMessage(""); const response = await fetch("/api/backups", { method: "POST" }); const data = await response.json(); setBusy(false); report(response.ok ? l(`备份完成：${data.manifest.files.length} 个文件已归档。`, `Backup complete: ${data.manifest.files.length} files archived.`) : data.message ?? l("备份失败", "Backup failed"), response.ok ? "success" : "error"); }
  async function saveStorageSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/settings/storage", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? l("存储设置保存失败", "Could not save storage settings"), "error"); setStorageSettings({ ...storageSettings!, ...data }); report(l("存储位置已保存。请完成数据迁移后重启 RelayDesk 使新路径生效。", "Storage location saved. Complete migration, then restart RelayDesk for the new path to take effect."), "success"); }
  async function createHost(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const response = await fetch("/api/agent-hosts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? l("主机登记失败", "Could not register host"), "error"); form.reset(); report(l("Agent Host 已登记，现在可以添加 Profile Agent。", "Agent host registered. You can now add a profile agent."), "success"); await load(); }
  async function createAgent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(l("正在验证真实 Hermes Endpoint…", "Verifying Hermes endpoint…")); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const host = hosts.find((item) => item.id === values.hostId); const baseUrl = `${values.protocol}://${host?.address}:${values.port}`; const response = await fetch("/api/agent-instances", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.name, hostId: values.hostId, profileName: values.profileName, sharingMode: values.sharingMode, apiKey: values.apiKey, baseUrl }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? l("Agent 登记失败", "Could not register agent"), "error"); form.reset(); report(l("真实 Hermes Agent 已验证并登记，请到成员授权页分配使用权限。", "Hermes agent verified and registered. Assign it from the Members page."), "success"); await load(); }
  async function toggleHost(host: AgentHost, confirmed = false) { if (host.enabled && !confirmed) { setPendingHostDisable(host); return; } const response = await fetch(`/api/agent-hosts/${host.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !host.enabled }) }); const data = await response.json(); const text = response.ok ? l(`主机已${host.enabled ? "停用" : "启用"}。`, `Host ${host.enabled ? "disabled" : "enabled"}.`) : data.message ?? l("主机更新失败", "Could not update host"); setMessage(text); notify(text, response.ok ? "success" : "error"); setPendingHostDisable(null); if (response.ok) await load(); }
  async function toggleAgent(agent: AgentInstance) { const response = await fetch(`/api/agent-instances/${agent.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !agent.enabled }) }); const data = await response.json(); report(response.ok ? l(`Agent 已${agent.enabled ? "停用" : "启用"}。`, `Agent ${agent.enabled ? "disabled" : "enabled"}.`) : data.message ?? l("Agent 更新失败", "Could not update agent"), response.ok ? "success" : "error"); if (response.ok) await load(); }
  async function rotateKey(event: FormEvent<HTMLFormElement>, agent: AgentInstance) { event.preventDefault(); setBusy(true); setMessage("正在使用新 Key 验证 Hermes…"); const apiKey = String(new FormData(event.currentTarget).get("apiKey") || ""); const response = await fetch(`/api/agent-instances/${agent.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ apiKey }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "Key 轮换失败", "error"); setRotatingAgentId(null); report("新 Key 已验证并完成加密轮换，现有会话无需重建。", "success"); await load(); }
  async function discoverAgents(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage("正在探测指定端口…"); setDiscovered([]); const values = Object.fromEntries(new FormData(event.currentTarget)); const ports = String(values.ports).split(/[,，\s]+/).map(Number).filter((port) => Number.isInteger(port)); const response = await fetch(`/api/agent-hosts/${values.hostId}/discover`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ protocol: values.protocol, ports, apiKey: values.apiKey }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "Profile 探测失败", "error"); setDiscovered(data); report(data.length ? `发现 ${data.length} 个可用 Hermes Endpoint。` : "指定端口未发现可用 Hermes API Server。", data.length ? "success" : "info"); }
  async function detectLocalProfiles() { setBusy(true); setMessage("正在检测本机 Hermes Profile…"); const response = await fetch("/api/agent-hosts/local-discovery"); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "本机 Profile 检测失败", "error"); setLocalProfiles(data); report(data.length ? `检测到 ${data.length} 个本机 Hermes Profile。` : "未检测到本机 Hermes Profile。", data.length ? "success" : "info"); }
  async function importLocalProfiles(profileNames: string[]) { setBusy(true); setMessage("正在关联本机 Profile…"); const response = await fetch("/api/agent-hosts/local-discovery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileNames }) }); const data = await response.json(); setBusy(false); if (!response.ok) { const text = data.message ?? "关联失败"; setMessage(text); notify(text, "error"); return; } const text = data.added?.length ? `已关联 ${data.added.length} 个本机 Agent，并可在成员授权页分配。` : "没有可关联的新 Profile。"; setLocalProfiles(data.discovered ?? []); setMessage(text); notify(text, data.added?.length ? "success" : "info"); await load(); }

  const capabilities = health?.runtime?.capabilities;
  const bootstrapSteps = [
    { key: "health", label: l("确认 RelayDesk 与 Hermes Runtime 健康", "Confirm RelayDesk and Hermes runtime health"), done: health?.status === "ok", action: l("刷新状态", "Refresh status") },
    { key: "local", label: l("检测并关联本机 Hermes Profile", "Detect and link local Hermes profiles"), done: localProfiles.some((profile) => profile.registered), action: l("检测本机 Profile", "Detect local profiles") },
    { key: "agent", label: l("验证至少一个可用 Agent", "Verify at least one available agent"), done: agents.some((agent) => agent.enabled && agentHealth[agent.id]?.status === "healthy"), action: l("检查 Agent", "Check agents") },
    { key: "member", label: l("为团队成员分配 Agent 使用权限", "Assign agent access to team members"), done: Boolean(memberAccess && memberAccess.activeMembers > 0 && memberAccess.membersWithoutChatAccess === 0), action: l("前往成员授权", "Open member access") },
  ];
  const tabs: { id: SettingsTab; label: string; admin?: boolean }[] = [{ id: "overview", label: l("概览与备份", "Overview & backups") }, { id: "storage", label: l("存储", "Storage"), admin: true }, { id: "setup", label: l("部署引导", "Setup guide"), admin: true }, { id: "agents", label: l("Agent 管理", "Agent management") }, { id: "audit", label: l("安全审计", "Security audit"), admin: true }];
  return <section className="standard-page settings-page"><div className="settings-title"><div><p className="eyebrow">{l("运行时与系统", "Runtime & System")}</p><h1>{l("系统设置", "System settings")}</h1><p className="muted">{l("按“电脑 → Hermes Profile → 成员授权”管理公司内网 Agent。", "Manage your internal agents through hosts, Hermes profiles, and member access.")}</p></div><button className="icon-refresh" onClick={load} aria-label={l("刷新状态", "Refresh status")} title={l("刷新状态", "Refresh status")}><RefreshCw size={18} /></button></div><div className="settings-tabs" role="tablist" aria-label={l("系统设置分区", "Settings sections")}>{tabs.filter((tab) => isAdmin || tab.id === "overview").map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={activeTab === tab.id} className={activeTab === tab.id ? "active" : undefined} onClick={() => setActiveTab(tab.id)}>{tab.label}</button>)}</div>
    <div className="settings-grid"><article><header><ServerCog size={20} /><h2>{l("RelayDesk 状态", "RelayDesk status")}</h2><span className={`health-dot ${health?.status === "ok" ? "ok" : ""}`}>{health?.status ?? l("检查中", "Checking")}</span></header><dl><div><dt>{l("默认运行时", "Default runtime")}</dt><dd>{health?.runtime?.type === "hermes" ? "Hermes Agent API Server" : health?.runtime?.type ?? l("检查中", "Checking")}</dd></div><div><dt>{l("数据库 / 存储", "Database / storage")}</dt><dd>{health?.database ?? "-"} / {health?.storage ?? "-"}</dd></div></dl>{capabilities ? <div className="runtime-capabilities"><span className={capabilities.streaming ? "enabled" : ""}>{l("流式", "Streaming")}</span><span className={capabilities.sessions ? "enabled" : ""}>{l("会话", "Sessions")}</span><span className={capabilities.attachments ? "enabled" : ""}>{l("附件", "Attachments")}</span><span className={capabilities.toolEvents ? "enabled" : ""}>{l("工具事件", "Tool events")}</span></div> : null}</article>
      <article><header><Archive size={20} /><h2>{l("数据与备份", "Data & backups")}</h2><span className="health-dot ok">{l("本地持久化", "Local persistence")}</span></header><p className="muted">{l("备份 SQLite、上传文件、Agent 产物及校验清单。", "Back up SQLite, uploaded files, agent artifacts, and the manifest.")}</p>{health?.security && !health.security.dedicatedCredentialsKey ? <p className="security-warning">{health.security.warning ?? l("生产环境请配置独立的 RELAYDESK_CREDENTIALS_KEY，再托管新的 Agent Key。", "Configure a dedicated RELAYDESK_CREDENTIALS_KEY before storing new agent keys in production.")}</p> : <p className="security-ok">{l("Agent 凭据使用独立主密钥加密。", "Agent credentials are encrypted with a dedicated master key.")}</p>}<button className="primary-button" onClick={backup} disabled={busy}>{busy ? l("正在处理", "Working") : l("立即备份", "Back up now")}</button></article></div>

    {isAdmin && storageSettings ? <article className="storage-settings-card"><header><HardDrive size={20} /><div><h2>{l("存储位置", "Storage locations")}</h2><p className="muted">{l("设置 RelayDesk 文件根目录与 SQLite 文件位置。上传文件、Hermes 同步产物、缩略图和备份均位于文件根目录内。", "Configure the RelayDesk data root and SQLite path. Uploads, Hermes artifacts, thumbnails, and backups live under the data root.")}</p></div></header><form onSubmit={saveStorageSettings}><label>{l("RelayDesk 文件根目录", "RelayDesk data root")}<input name="dataDir" defaultValue={storageSettings.dataDir} required /></label><label>{l("SQLite 数据库文件", "SQLite database file")} <Database size={14} /><input name="databasePath" defaultValue={storageSettings.databasePath} required /></label><p className="security-warning">{l("修改路径不会自动搬运现有数据。请先创建备份、迁移现有文件与数据库，再重启服务使配置生效。", "Changing paths does not move existing data. Create a backup, migrate files and database, then restart the service for the new configuration to take effect.")}</p><button className="primary-button" disabled={busy}>{busy ? l("正在保存", "Saving") : l("保存并等待重启", "Save and restart later")}</button></form></article> : null}

    {isAdmin ? <section className="bootstrap-guide"><header><div><p className="eyebrow">{l("首次运行引导", "First-run guide")}</p><h2>{l("部署引导", "Setup guide")}</h2><p className="muted">{l("按顺序完成以下步骤，即可让成员开始与已授权的 Hermes Agent 私聊。", "Complete these steps to let members chat with authorized Hermes agents.")}</p></div><UsersRound size={22} /></header><ol>{bootstrapSteps.map((step, index) => <li key={step.key} className={step.done ? "complete" : ""}>{step.done ? <CheckCircle2 size={19} /> : <Circle size={19} />}<span><b>{index + 1}. {step.label}</b><small>{step.key === "member" && memberAccess ? (memberAccess.activeMembers ? l(`${memberAccess.membersWithChatAccess}/${memberAccess.activeMembers} 位活跃成员已获聊天权限`, `${memberAccess.membersWithChatAccess}/${memberAccess.activeMembers} active members have chat access`) : l("尚未创建成员", "No members created yet")) : step.done ? l("已完成", "Complete") : l("待完成", "Pending")}</small></span>{step.key === "local" ? <button className="secondary-button" onClick={detectLocalProfiles} disabled={busy}>{l("重新检测", "Detect again")}</button> : step.key === "member" ? <button className="secondary-button" onClick={() => window.location.assign("/members")}>{l("去授权", "Manage access")}</button> : <button className="secondary-button" onClick={load}> {step.action}</button>}</li>)}</ol></section> : null}

    <div className="settings-section-heading"><div><p className="eyebrow">{l("Agent 集群", "Agent fleet")}</p><h2>{l("Hermes 主机与 Profile", "Hermes hosts and profiles")}</h2></div><span>{l(`${hosts.length} 台电脑 · ${agents.length} 个 Agent`, `${hosts.length} hosts · ${agents.length} agents`)}</span></div>
    <div className="host-grid">{hosts.map((host) => <article key={host.id} className={!host.enabled ? "disabled" : ""}><header><Server size={18} /><div><strong>{host.name}</strong><code>{host.address}</code></div><span className={`health-dot ${host.enabled ? "ok" : ""}`}>{host.enabled ? l("启用", "Enabled") : l("停用", "Disabled")}</span></header><p>{host.description || l("未填写备注", "No note provided")}</p><footer><span>{l(`${host.agentCount} 个 Profile Agent`, `${host.agentCount} profile agents`)}</span>{isAdmin ? <button className="secondary-button" onClick={() => toggleHost(host)}>{host.enabled ? l("停用主机", "Disable host") : l("启用主机", "Enable host")}</button> : null}</footer></article>)}</div>

    {isAdmin ? <article className="local-profile-card"><header><div><p className="eyebrow">{l("本机引导", "Local bootstrap")}</p><h2>{l("自动检测本机 Hermes", "Detect local Hermes automatically")}</h2><p className="muted">{l("进入设置页会自动检测当前电脑的 Hermes Profiles、API 端口和健康状态；不会把 API Key 返回浏览器。", "Opening Settings detects local Hermes profiles, API ports, and health without returning API keys to the browser.")}</p></div><div className="local-profile-actions"><button className="secondary-button" onClick={detectLocalProfiles} disabled={busy}>{l("重新检测", "Detect again")}</button><button className="primary-button" disabled={busy || !localProfiles.some((profile) => profile.status === "healthy" && !profile.registered)} onClick={() => void importLocalProfiles(localProfiles.filter((profile) => profile.status === "healthy" && !profile.registered).map((profile) => profile.profileName))}>{l("一键关联可用 Profile", "Link available profiles")}</button></div></header>{localProfiles.length ? <div className="local-profile-list">{localProfiles.map((profile) => <div key={profile.profileName}><span className={`health-dot ${profile.status === "healthy" ? "ok" : ""}`}>{profile.status}</span><section><strong>{profile.profileName}</strong><small>{profile.baseUrl ?? l("未配置 API Server", "API server not configured")}{profile.modelName ? ` · ${profile.modelName}` : ""}</small></section>{profile.registered ? <span className="status-chip ready">{l("已关联", "Linked")}</span> : <button className="primary-button" disabled={profile.status !== "healthy"} onClick={() => void importLocalProfiles([profile.profileName])}>{l("关联到 RelayDesk", "Link to RelayDesk")}</button>}</div>)}</div> : <p className="muted">{l("正在等待本机 Profile 检测结果。", "Waiting for local profile detection.")}</p>}</article> : null}

    <div className="agent-fleet-list">{agents.map((agent) => { const state = agentHealth[agent.id]; return <article key={agent.id} className={!agent.enabled ? "disabled" : ""}><span className="agent-icon"><Bot size={18} /></span><div><strong>{agent.name}</strong><small>{agent.hostName ?? l("未归类主机", "Unassigned host")} · {l("Profile", "Profile")}: {agent.profileName || agent.workspaceLabel}</small><code>{agent.baseUrl}</code>{rotatingAgentId === agent.id ? <form className="key-rotation-form" onSubmit={(event) => rotateKey(event, agent)}><input name="apiKey" type="password" minLength={8} autoComplete="new-password" placeholder={l("输入新的 API_SERVER_KEY", "Enter new API_SERVER_KEY")} required /><button className="primary-button" disabled={busy}>{l("验证并轮换", "Verify and rotate")}</button><button type="button" className="secondary-button" onClick={() => setRotatingAgentId(null)}>{l("取消", "Cancel")}</button></form> : null}</div><span className={`mode-chip ${agent.sharingMode}`}>{agent.sharingMode === "dedicated" ? l("成员独占", "Dedicated") : l("多人共享", "Shared")}</span><span className="mode-chip">{agent.attachmentSupport === "files" ? l("可发文件", "Files") : l("仅图片", "Images only")}</span><span className={`health-dot ${state?.status === "healthy" ? "ok" : ""}`}>{agent.enabled ? state?.status ?? l("检查中", "Checking") : l("已停用", "Disabled")}</span>{isAdmin && agent.id !== "hermes-default" ? <div className="agent-admin-actions"><button className="secondary-button" onClick={() => setRotatingAgentId(agent.id)}>{l("轮换 Key", "Rotate key")}</button><button className="secondary-button" onClick={() => toggleAgent(agent)}>{agent.enabled ? l("停用", "Disable") : l("启用", "Enable")}</button></div> : null}</article>; })}</div>

    {isAdmin ? <><article className="discovery-card"><header><RefreshCw size={20} /><h2>{l("发现新 Hermes Profile", "Discover Hermes profiles")}</h2></header><p className="muted">{l("只探测管理员明确填写的端口，不执行整网或全端口扫描。Key 仅用于本次探测，不会保存。", "Only explicitly specified ports are probed. RelayDesk never scans the full network or all ports, and this key is not stored.")}</p><form className="discovery-form" onSubmit={discoverAgents}><select name="hostId" required defaultValue=""><option value="" disabled>{l("选择 Agent Host", "Select agent host")}</option>{hosts.filter((host) => host.enabled).map((host) => <option key={host.id} value={host.id}>{host.name} · {host.address}</option>)}</select><select name="protocol" defaultValue="http"><option value="http">HTTP</option><option value="https">HTTPS</option></select><input name="ports" placeholder={l("端口：8642, 8643, 8644", "Ports: 8642, 8643, 8644")} required /><input name="apiKey" type="password" minLength={8} placeholder={l("用于探测的 API_SERVER_KEY", "API_SERVER_KEY for this probe")} required /><button className="primary-button" disabled={busy}>{l("探测 Profile", "Probe profiles")}</button></form>{discovered.length ? <div className="discovery-results">{discovered.map((item) => <span key={item.baseUrl}><strong>{item.profiles.map((profile) => profile.name).join(", ") || "Hermes Agent"}</strong><code>{item.baseUrl}</code></span>)}</div> : null}</article><div className="admin-provision-grid"><article><header><Plus size={20} /><h2>{l("1. 登记 Agent Host", "1. Register an agent host")}</h2></header><p className="muted">{l("登记运行 Hermes 的本机或其他内网电脑。仅允许私有 IP 或管理员白名单主机。", "Register the local machine or another internal host running Hermes. Only private IPs or allow-listed hosts are permitted.")}</p><form className="agent-create-form" onSubmit={createHost}><input name="name" placeholder={l("电脑名称，例如：内容工作站 01", "Computer name, e.g. Studio 01")} required /><input name="address" placeholder={l("内网 IP，例如：192.168.1.20", "Internal IP, e.g. 192.168.1.20")} required /><input name="description" placeholder={l("位置或用途（可选）", "Location or purpose (optional)")} /><button className="primary-button" disabled={busy}>{l("登记主机", "Register host")}</button></form></article>
      <article><header><Plus size={20} /><h2>{l("2. 添加 Hermes Profile", "2. Add a Hermes profile")}</h2></header><p className="muted">{l("每个 Profile 必须使用独立端口。提交前会真实验证 Hermes API Server。", "Every profile must use a dedicated port. RelayDesk verifies the Hermes API server before saving.")}</p><form className="agent-create-form" onSubmit={createAgent}><select name="hostId" required defaultValue=""><option value="" disabled>{l("选择 Agent Host", "Select agent host")}</option>{hosts.filter((host) => host.enabled).map((host) => <option key={host.id} value={host.id}>{host.name} · {host.address}</option>)}</select><input name="name" placeholder={l("显示名称，例如：内容 Agent", "Display name, e.g. Research agent")} required /><input name="profileName" pattern="[A-Za-z0-9_-]+" placeholder={l("Hermes Profile，例如：content", "Hermes profile, e.g. research")} required /><div className="endpoint-fields"><select name="protocol" defaultValue="http"><option value="http">HTTP</option><option value="https">HTTPS</option></select><input name="port" inputMode="numeric" pattern="[0-9]+" placeholder={l("端口，例如：8643", "Port, e.g. 8643")} required /></div><select name="sharingMode" defaultValue="shared"><option value="shared">{l("多人共享 Profile", "Shared profile")}</option><option value="dedicated">{l("单成员独占 Profile", "Dedicated profile")}</option></select><input name="apiKey" type="password" minLength={8} autoComplete="new-password" placeholder={l("Hermes API_SERVER_KEY（加密保存）", "Hermes API_SERVER_KEY (encrypted)")} required /><button className="primary-button" disabled={busy || !hosts.some((host) => host.enabled)}>{l("验证并登记 Agent", "Verify and register agent")}</button></form></article></div></> : null}
    {isAdmin ? <section className="audit-panel"><div className="settings-section-heading"><div><p className="eyebrow">{l("安全审计", "Security audit")}</p><h2>{l("最近管理操作", "Recent administration")}</h2></div><span>{l(`最近 ${auditLogs.length} 条`, `Latest ${auditLogs.length}`)}</span></div><div className="audit-list">{auditLogs.map((log) => <article key={log.id}><time>{new Date(log.createdAt).toLocaleString(locale)}</time><strong>{log.action}</strong><span>{log.operatorName || l("系统", "System")}</span><code>{log.targetType}{log.targetId ? ` · ${log.targetId.slice(0, 8)}` : ""}</code></article>)}{!auditLogs.length ? <p className="muted">{l("尚无管理操作记录。", "No administration activity yet.")}</p> : null}</div></section> : null}
    {message ? <p className="settings-message">{message}</p> : null}
    <ConfirmDialog open={Boolean(pendingHostDisable)} title={l("停用 Agent Host", "Disable agent host")} description={l(`停用“${pendingHostDisable?.name ?? ""}”会同时停用它下面的全部 Agent，并立即撤销新请求。`, `Disabling “${pendingHostDisable?.name ?? ""}” will disable all of its agents and immediately block new requests.`)} confirmLabel={l("确认停用", "Disable host")} destructive onConfirm={() => pendingHostDisable && void toggleHost(pendingHostDisable, true)} onCancel={() => setPendingHostDisable(null)} />
  </section>;
}
