"use client";

import { type FormEvent, useEffect, useState } from "react";
import { Archive, Bot, CheckCircle2, Circle, Database, HardDrive, Plus, RefreshCw, Server, ServerCog, UsersRound } from "lucide-react";
import { ConfirmDialog } from "@/shared/components/confirm-dialog";
import { useToast } from "@/shared/components/toast-provider";

type Capabilities = { streaming: boolean; sessions: boolean; toolEvents: boolean; cancellation: boolean; attachments?: boolean };
type Health = { status: string; database?: string; storage?: string; security?: { dedicatedCredentialsKey: boolean; warning?: string }; runtime?: { status: string; message?: string; type?: string; capabilities?: Capabilities } };
type AgentHost = { id: string; name: string; address: string; description: string | null; enabled: boolean; agentCount: number };
type AgentInstance = { id: string; name: string; type: string; baseUrl: string; workspaceLabel: string; profileName: string; hostId: string | null; hostName: string | null; sharingMode: "shared" | "dedicated"; credentialMode: string; attachmentSupport: "files" | "images_only"; enabled: boolean };
type AgentHealth = { status: string; message?: string; capabilities?: Capabilities };
type AuditLog = { id: string; action: string; targetType: string; targetId: string | null; detailJson: string; operatorName: string | null; createdAt: number };
type DiscoveredAgent = { baseUrl: string; port: number; profiles: { id: string; name: string }[] };
type LocalProfile = { profileName: string; baseUrl: string | null; status: "healthy" | "offline" | "incomplete"; modelName: string | null; registered: boolean; hasApiKey: boolean };
type MemberAccessSummary = { activeMembers: number; membersWithChatAccess: number; membersWithoutChatAccess: number };
type StorageSettings = { dataDir: string; databasePath: string; storageConfigPath: string; restartRequired: boolean };

export default function SettingsPage() {
  const [health, setHealth] = useState<Health>();
  const [hosts, setHosts] = useState<AgentHost[]>([]);
  const [agents, setAgents] = useState<AgentInstance[]>([]);
  const [isAdmin, setIsAdmin] = useState(false);
  const [agentHealth, setAgentHealth] = useState<Record<string, AgentHealth>>({});
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [rotatingAgentId, setRotatingAgentId] = useState<string | null>(null);
  const [discovered, setDiscovered] = useState<DiscoveredAgent[]>([]);
  const [localProfiles, setLocalProfiles] = useState<LocalProfile[]>([]);
  const [memberAccess, setMemberAccess] = useState<MemberAccessSummary>();
  const [storageSettings, setStorageSettings] = useState<StorageSettings>();
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [pendingHostDisable, setPendingHostDisable] = useState<AgentHost | null>(null);
  const { notify } = useToast();
  const report = (text: string, tone: "success" | "error" | "info" = "info") => { setMessage(text); notify(text, tone); };

  async function load() {
    const [healthResponse, authorizedResponse, allResponse, hostsResponse, auditResponse] = await Promise.all([fetch("/api/health"), fetch("/api/agents"), fetch("/api/agent-instances"), fetch("/api/agent-hosts"), fetch("/api/audit-logs?limit=30")]);
    setHealth(await healthResponse.json());
    const authorized = authorizedResponse.ok ? await authorizedResponse.json() as AgentInstance[] : [];
    const admin = allResponse.ok; const visible = admin ? await allResponse.json() as AgentInstance[] : authorized;
    setIsAdmin(admin); setAgents(visible); setHosts(hostsResponse.ok ? await hostsResponse.json() : []); setAuditLogs(auditResponse.ok ? await auditResponse.json() : []);
    if (admin) {
      const [localResponse, accessResponse, storageResponse] = await Promise.all([fetch("/api/agent-hosts/local-discovery"), fetch("/api/members/access-summary"), fetch("/api/settings/storage")]);
      if (localResponse.ok) setLocalProfiles(await localResponse.json());
      if (accessResponse.ok) setMemberAccess(await accessResponse.json());
      if (storageResponse.ok) setStorageSettings(await storageResponse.json());
    }
    const checks = await Promise.all(visible.filter((agent) => agent.enabled).map(async (agent) => { const response = await fetch(`/api/agents/${agent.id}/health`); return [agent.id, response.ok ? await response.json() : { status: "offline", message: "健康检查失败" }] as const; }));
    setAgentHealth(Object.fromEntries(checks));
  }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);

  async function backup() { setBusy(true); setMessage(""); const response = await fetch("/api/backups", { method: "POST" }); const data = await response.json(); setBusy(false); report(response.ok ? `备份完成：${data.manifest.files.length} 个文件已归档。` : data.message ?? "备份失败", response.ok ? "success" : "error"); }
  async function saveStorageSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/settings/storage", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "存储设置保存失败", "error"); setStorageSettings({ ...storageSettings!, ...data }); report("存储位置已保存。请完成数据迁移后重启 RelayDesk 使新路径生效。", "success"); }
  async function createHost(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = event.currentTarget; const response = await fetch("/api/agent-hosts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "主机登记失败", "error"); form.reset(); report("Agent Host 已登记，现在可以添加 Profile Agent。", "success"); await load(); }
  async function createAgent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage("正在验证真实 Hermes Endpoint…"); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const host = hosts.find((item) => item.id === values.hostId); const baseUrl = `${values.protocol}://${host?.address}:${values.port}`; const response = await fetch("/api/agent-instances", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.name, hostId: values.hostId, profileName: values.profileName, sharingMode: values.sharingMode, apiKey: values.apiKey, baseUrl }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "Agent 登记失败", "error"); form.reset(); report("真实 Hermes Agent 已验证并登记，请到成员授权页分配使用权限。", "success"); await load(); }
  async function toggleHost(host: AgentHost, confirmed = false) { if (host.enabled && !confirmed) { setPendingHostDisable(host); return; } const response = await fetch(`/api/agent-hosts/${host.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !host.enabled }) }); const data = await response.json(); const text = response.ok ? `主机已${host.enabled ? "停用" : "启用"}。` : data.message ?? "主机更新失败"; setMessage(text); notify(text, response.ok ? "success" : "error"); setPendingHostDisable(null); if (response.ok) await load(); }
  async function toggleAgent(agent: AgentInstance) { const response = await fetch(`/api/agent-instances/${agent.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: !agent.enabled }) }); const data = await response.json(); report(response.ok ? `Agent 已${agent.enabled ? "停用" : "启用"}。` : data.message ?? "Agent 更新失败", response.ok ? "success" : "error"); if (response.ok) await load(); }
  async function rotateKey(event: FormEvent<HTMLFormElement>, agent: AgentInstance) { event.preventDefault(); setBusy(true); setMessage("正在使用新 Key 验证 Hermes…"); const apiKey = String(new FormData(event.currentTarget).get("apiKey") || ""); const response = await fetch(`/api/agent-instances/${agent.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ apiKey }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "Key 轮换失败", "error"); setRotatingAgentId(null); report("新 Key 已验证并完成加密轮换，现有会话无需重建。", "success"); await load(); }
  async function discoverAgents(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage("正在探测指定端口…"); setDiscovered([]); const values = Object.fromEntries(new FormData(event.currentTarget)); const ports = String(values.ports).split(/[,，\s]+/).map(Number).filter((port) => Number.isInteger(port)); const response = await fetch(`/api/agent-hosts/${values.hostId}/discover`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ protocol: values.protocol, ports, apiKey: values.apiKey }) }); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "Profile 探测失败", "error"); setDiscovered(data); report(data.length ? `发现 ${data.length} 个可用 Hermes Endpoint。` : "指定端口未发现可用 Hermes API Server。", data.length ? "success" : "info"); }
  async function detectLocalProfiles() { setBusy(true); setMessage("正在检测本机 Hermes Profile…"); const response = await fetch("/api/agent-hosts/local-discovery"); const data = await response.json(); setBusy(false); if (!response.ok) return report(data.message ?? "本机 Profile 检测失败", "error"); setLocalProfiles(data); report(data.length ? `检测到 ${data.length} 个本机 Hermes Profile。` : "未检测到本机 Hermes Profile。", data.length ? "success" : "info"); }
  async function importLocalProfiles(profileNames: string[]) { setBusy(true); setMessage("正在关联本机 Profile…"); const response = await fetch("/api/agent-hosts/local-discovery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileNames }) }); const data = await response.json(); setBusy(false); if (!response.ok) { const text = data.message ?? "关联失败"; setMessage(text); notify(text, "error"); return; } const text = data.added?.length ? `已关联 ${data.added.length} 个本机 Agent，并可在成员授权页分配。` : "没有可关联的新 Profile。"; setLocalProfiles(data.discovered ?? []); setMessage(text); notify(text, data.added?.length ? "success" : "info"); await load(); }

  const capabilities = health?.runtime?.capabilities;
  const bootstrapSteps = [
    { label: "确认 RelayDesk 与 Hermes Runtime 健康", done: health?.status === "ok", action: "刷新状态" },
    { label: "检测并关联本机 Hermes Profile", done: localProfiles.some((profile) => profile.registered), action: "检测本机 Profile" },
    { label: "验证至少一个可用 Agent", done: agents.some((agent) => agent.enabled && agentHealth[agent.id]?.status === "healthy"), action: "检查 Agent" },
    { label: "为团队成员分配 Agent 使用权限", done: Boolean(memberAccess && memberAccess.activeMembers > 0 && memberAccess.membersWithoutChatAccess === 0), action: "前往成员授权" },
  ];
  return <section className="standard-page settings-page"><div className="settings-title"><div><p className="eyebrow">Runtime &amp; System</p><h1>系统设置</h1><p className="muted">按“电脑 → Hermes Profile → 成员授权”管理公司内网 Agent。</p></div><button className="icon-refresh" onClick={load} aria-label="刷新状态"><RefreshCw size={18} /></button></div>
    <div className="settings-grid"><article><header><ServerCog size={20} /><h2>RelayDesk 状态</h2><span className={`health-dot ${health?.status === "ok" ? "ok" : ""}`}>{health?.status ?? "检查中"}</span></header><dl><div><dt>默认 Runtime</dt><dd>{health?.runtime?.type === "hermes" ? "Hermes Agent API Server" : health?.runtime?.type ?? "检查中"}</dd></div><div><dt>数据库 / 存储</dt><dd>{health?.database ?? "-"} / {health?.storage ?? "-"}</dd></div></dl>{capabilities ? <div className="runtime-capabilities"><span className={capabilities.streaming ? "enabled" : ""}>流式</span><span className={capabilities.sessions ? "enabled" : ""}>会话</span><span className={capabilities.attachments ? "enabled" : ""}>附件</span><span className={capabilities.toolEvents ? "enabled" : ""}>工具事件</span></div> : null}</article>
      <article><header><Archive size={20} /><h2>数据与备份</h2><span className="health-dot ok">本地持久化</span></header><p className="muted">备份 SQLite、上传文件、Agent 产物及校验清单。</p>{health?.security && !health.security.dedicatedCredentialsKey ? <p className="security-warning">{health.security.warning ?? "生产环境请配置独立的 RELAYDESK_CREDENTIALS_KEY，再托管新的 Agent Key。"}</p> : <p className="security-ok">Agent 凭据使用独立主密钥加密。</p>}<button className="primary-button" onClick={backup} disabled={busy}>{busy ? "正在处理" : "立即备份"}</button></article></div>

    {isAdmin && storageSettings ? <article className="storage-settings-card"><header><HardDrive size={20} /><div><h2>存储位置</h2><p className="muted">设置 RelayDesk 文件根目录与 SQLite 文件位置。上传文件、Hermes 同步产物、缩略图和备份均位于文件根目录内。</p></div></header><form onSubmit={saveStorageSettings}><label>RelayDesk 文件根目录<input name="dataDir" defaultValue={storageSettings.dataDir} required /></label><label>SQLite 数据库文件 <Database size={14} /><input name="databasePath" defaultValue={storageSettings.databasePath} required /></label><p className="security-warning">修改路径不会自动搬运现有数据。请先创建备份、迁移现有文件与数据库，再重启服务使配置生效。</p><button className="primary-button" disabled={busy}>{busy ? "正在保存" : "保存并等待重启"}</button></form></article> : null}

    {isAdmin ? <section className="bootstrap-guide"><header><div><p className="eyebrow">First-run Guide</p><h2>部署引导</h2><p className="muted">按顺序完成以下步骤，即可让成员开始与已授权的 Hermes Agent 私聊。</p></div><UsersRound size={22} /></header><ol>{bootstrapSteps.map((step, index) => <li key={step.label} className={step.done ? "complete" : ""}>{step.done ? <CheckCircle2 size={19} /> : <Circle size={19} />}<span><b>{index + 1}. {step.label}</b><small>{step.label.includes("成员") && memberAccess ? (memberAccess.activeMembers ? `${memberAccess.membersWithChatAccess}/${memberAccess.activeMembers} 位活跃成员已获聊天权限` : "尚未创建成员") : step.done ? "已完成" : "待完成"}</small></span>{step.label.includes("本机") ? <button className="secondary-button" onClick={detectLocalProfiles} disabled={busy}>重新检测</button> : step.label.includes("成员") ? <button className="secondary-button" onClick={() => window.location.assign("/members")}>去授权</button> : <button className="secondary-button" onClick={load}> {step.action}</button>}</li>)}</ol></section> : null}

    <div className="settings-section-heading"><div><p className="eyebrow">Agent Fleet</p><h2>Hermes 主机与 Profile</h2></div><span>{hosts.length} 台电脑 · {agents.length} 个 Agent</span></div>
    <div className="host-grid">{hosts.map((host) => <article key={host.id} className={!host.enabled ? "disabled" : ""}><header><Server size={18} /><div><strong>{host.name}</strong><code>{host.address}</code></div><span className={`health-dot ${host.enabled ? "ok" : ""}`}>{host.enabled ? "启用" : "停用"}</span></header><p>{host.description || "未填写备注"}</p><footer><span>{host.agentCount} 个 Profile Agent</span>{isAdmin ? <button className="secondary-button" onClick={() => toggleHost(host)}>{host.enabled ? "停用主机" : "启用主机"}</button> : null}</footer></article>)}</div>

    {isAdmin ? <article className="local-profile-card"><header><div><p className="eyebrow">Local Bootstrap</p><h2>自动检测本机 Hermes</h2><p className="muted">进入设置页会自动检测当前电脑的 Hermes Profiles、API 端口和健康状态；不会把 API Key 返回浏览器。</p></div><div className="local-profile-actions"><button className="secondary-button" onClick={detectLocalProfiles} disabled={busy}>重新检测</button><button className="primary-button" disabled={busy || !localProfiles.some((profile) => profile.status === "healthy" && !profile.registered)} onClick={() => void importLocalProfiles(localProfiles.filter((profile) => profile.status === "healthy" && !profile.registered).map((profile) => profile.profileName))}>一键关联可用 Profile</button></div></header>{localProfiles.length ? <div className="local-profile-list">{localProfiles.map((profile) => <div key={profile.profileName}><span className={`health-dot ${profile.status === "healthy" ? "ok" : ""}`}>{profile.status}</span><section><strong>{profile.profileName}</strong><small>{profile.baseUrl ?? "未配置 API Server"}{profile.modelName ? ` · ${profile.modelName}` : ""}</small></section>{profile.registered ? <span className="status-chip ready">已关联</span> : <button className="primary-button" disabled={profile.status !== "healthy"} onClick={() => void importLocalProfiles([profile.profileName])}>关联到 RelayDesk</button>}</div>)}</div> : <p className="muted">正在等待本机 Profile 检测结果。</p>}</article> : null}

    <div className="agent-fleet-list">{agents.map((agent) => { const state = agentHealth[agent.id]; return <article key={agent.id} className={!agent.enabled ? "disabled" : ""}><span className="agent-icon"><Bot size={18} /></span><div><strong>{agent.name}</strong><small>{agent.hostName ?? "未归类主机"} · Profile: {agent.profileName || agent.workspaceLabel}</small><code>{agent.baseUrl}</code>{rotatingAgentId === agent.id ? <form className="key-rotation-form" onSubmit={(event) => rotateKey(event, agent)}><input name="apiKey" type="password" minLength={8} autoComplete="new-password" placeholder="输入新的 API_SERVER_KEY" required /><button className="primary-button" disabled={busy}>验证并轮换</button><button type="button" className="secondary-button" onClick={() => setRotatingAgentId(null)}>取消</button></form> : null}</div><span className={`mode-chip ${agent.sharingMode}`}>{agent.sharingMode === "dedicated" ? "成员独占" : "多人共享"}</span><span className="mode-chip">{agent.attachmentSupport === "files" ? "可发文件" : "仅图片"}</span><span className={`health-dot ${state?.status === "healthy" ? "ok" : ""}`}>{agent.enabled ? state?.status ?? "检查中" : "已停用"}</span>{isAdmin && agent.id !== "hermes-default" ? <div className="agent-admin-actions"><button className="secondary-button" onClick={() => setRotatingAgentId(agent.id)}>轮换 Key</button><button className="secondary-button" onClick={() => toggleAgent(agent)}>{agent.enabled ? "停用" : "启用"}</button></div> : null}</article>; })}</div>

    {isAdmin ? <><article className="discovery-card"><header><RefreshCw size={20} /><h2>发现新 Hermes Profile</h2></header><p className="muted">只探测管理员明确填写的端口，不执行整网或全端口扫描。Key 仅用于本次探测，不会保存。</p><form className="discovery-form" onSubmit={discoverAgents}><select name="hostId" required defaultValue=""><option value="" disabled>选择 Agent Host</option>{hosts.filter((host) => host.enabled).map((host) => <option key={host.id} value={host.id}>{host.name} · {host.address}</option>)}</select><select name="protocol" defaultValue="http"><option value="http">HTTP</option><option value="https">HTTPS</option></select><input name="ports" placeholder="端口：8642, 8643, 8644" required /><input name="apiKey" type="password" minLength={8} placeholder="用于探测的 API_SERVER_KEY" required /><button className="primary-button" disabled={busy}>探测 Profile</button></form>{discovered.length ? <div className="discovery-results">{discovered.map((item) => <span key={item.baseUrl}><strong>{item.profiles.map((profile) => profile.name).join(", ") || "Hermes Agent"}</strong><code>{item.baseUrl}</code></span>)}</div> : null}</article><div className="admin-provision-grid"><article><header><Plus size={20} /><h2>1. 登记 Agent Host</h2></header><p className="muted">登记运行 Hermes 的本机或其他内网电脑。仅允许私有 IP 或管理员白名单主机。</p><form className="agent-create-form" onSubmit={createHost}><input name="name" placeholder="电脑名称，例如：内容工作站 01" required /><input name="address" placeholder="内网 IP，例如：192.168.1.20" required /><input name="description" placeholder="位置或用途（可选）" /><button className="primary-button" disabled={busy}>登记主机</button></form></article>
      <article><header><Plus size={20} /><h2>2. 添加 Hermes Profile</h2></header><p className="muted">每个 Profile 必须使用独立端口。提交前会真实验证 Hermes API Server。</p><form className="agent-create-form" onSubmit={createAgent}><select name="hostId" required defaultValue=""><option value="" disabled>选择 Agent Host</option>{hosts.filter((host) => host.enabled).map((host) => <option key={host.id} value={host.id}>{host.name} · {host.address}</option>)}</select><input name="name" placeholder="显示名称，例如：内容 Agent" required /><input name="profileName" pattern="[A-Za-z0-9_-]+" placeholder="Hermes Profile，例如：content" required /><div className="endpoint-fields"><select name="protocol" defaultValue="http"><option value="http">HTTP</option><option value="https">HTTPS</option></select><input name="port" inputMode="numeric" pattern="[0-9]+" placeholder="端口，例如：8643" required /></div><select name="sharingMode" defaultValue="shared"><option value="shared">多人共享 Profile</option><option value="dedicated">单成员独占 Profile</option></select><input name="apiKey" type="password" minLength={8} autoComplete="new-password" placeholder="Hermes API_SERVER_KEY（加密保存）" required /><button className="primary-button" disabled={busy || !hosts.some((host) => host.enabled)}>验证并登记 Agent</button></form></article></div></> : null}
    {isAdmin ? <section className="audit-panel"><div className="settings-section-heading"><div><p className="eyebrow">Security Audit</p><h2>最近管理操作</h2></div><span>最近 {auditLogs.length} 条</span></div><div className="audit-list">{auditLogs.map((log) => <article key={log.id}><time>{new Date(log.createdAt).toLocaleString("zh-CN")}</time><strong>{log.action}</strong><span>{log.operatorName || "系统"}</span><code>{log.targetType}{log.targetId ? ` · ${log.targetId.slice(0, 8)}` : ""}</code></article>)}{!auditLogs.length ? <p className="muted">尚无管理操作记录。</p> : null}</div></section> : null}
    {message ? <p className="settings-message">{message}</p> : null}
    <ConfirmDialog open={Boolean(pendingHostDisable)} title="停用 Agent Host" description={`停用“${pendingHostDisable?.name ?? ""}”会同时停用它下面的全部 Agent，并立即撤销新请求。`} confirmLabel="确认停用" destructive onConfirm={() => pendingHostDisable && void toggleHost(pendingHostDisable, true)} onCancel={() => setPendingHostDisable(null)} />
  </section>;
}
