import type { Locale } from "@/shared/i18n/locale-provider";

export const systemMessages = {
  en: {
    chat: "Chats", members: "Members", settings: "Settings",
    newConversation: "New conversation", collapse: "Collapse sidebar", expand: "Expand sidebar", logout: "Sign out", administrator: "Administrator", member: "Member",
    loginTitle: "Enter your workspace", loginDescription: "Use your authorized member account to collaborate with Hermes Agent.", memberName: "Member name", memberNamePlaceholder: "For example: Alex", password: "Password", passwordPlaceholder: "Enter your password", signIn: "Enter RelayDesk", verifying: "Verifying", loginFailed: "Sign-in failed. Please try again.", internalOnly: "For authorized internal members only", firstUse: "On first use, the workspace password creates the first administrator.",
    loginKicker: "TEAM AI WORKSPACE", loginHero: "Turn every Agent conversation into organized team work", loginHeroDescription: "RelayDesk connects team members with Hermes Agent and preserves conversations, files, and work outcomes as reusable team assets.",
    connected: "Connected", agentConversation: "Conversation with Hermes Agent", previewUserInitial: "A", previewUserMessage: "Please summarize the key decisions and follow-up actions from this product review.", previewTime: "09:41", previewAgentIntro: "Here is a structured summary:", previewPointOne: "Confirm the core scope and priorities", previewPointTwo: "Deliver the technical plan in stages", previewPointThree: "Add data-access validation", previewFollowUp: "Follow-up actions", previewActionOne: "Complete the PRD and flow diagrams", previewActionTwo: "Assess the API migration impact", previewComposer: "Message Hermes Agent…", agentHealthy: "Healthy and ready", viewAgentStatus: "View Agent status", archivedWork: "Archived work", archiveFileName: "Product review notes.md", archiveLocation: "Team knowledge base / Project Alpha", archiveBy: "Archived by Alex on 2026-07-11", archiveDescription: "Includes decisions, action items, and related discussion history.", viewDetails: "View details", internalWorkspace: "Internal team workspace",
    searchChats: "Search chats", searchArchivedChats: "Search archived chats", viewArchive: "View archive", returnToCurrent: "Current chats", archive: "Archive", restore: "Restore", rename: "Rename", sync: "Sync", syncing: "Syncing", delete: "Delete", pin: "Pin", unpin: "Unpin", currentChat: "Current chat", archivedChat: "Archived chat", createFirstChat: "Create your first chat", noAuthorizedAgent: "No authorized Agent", messagePlaceholder: "Describe what you want to create, review, or change…", sendMessage: "Send message", addAttachment: "Add attachment", stopRun: "Stop run",
    close: "Close", cancel: "Cancel", confirm: "Confirm", save: "Save", name: "Name", systemNotifications: "System notifications", closeNotification: "Dismiss notification",
    checkingRuntime: "Checking Runtime", hermesConnected: "Hermes Agent connected", mockConnected: "Mock Runtime connected", runtimeDisconnected: "Runtime disconnected",
    syncFailed: "Sync failed. Local history was kept; try again later.", networkInterrupted: "Network connection interrupted. RelayDesk local history was kept; try syncing again later.",
    sessionNotFound: "Hermes could not find this chat. Your RelayDesk history has been kept.", conversationNotFound: "This chat is no longer available in RelayDesk.", agentAccessRevoked: "Your access to this Agent's chat history has been revoked.", unauthenticated: "Your session has expired. Sign in again to continue.", runtimeUnavailable: "Hermes is temporarily unavailable. Your RelayDesk history has been kept; try syncing again later.", runtimeAuthFailed: "Hermes authorization has expired. Ask an administrator to check the agent key.", streamInterrupted: "The response stream was interrupted. Received content has been kept.", runtimeError: "Hermes could not complete this request. Please try again later.",
    inputRestored: "Your previous message and attachments were restored. Review and send again when ready.", loadingAgents: "Loading Agents. Please wait.", noAvailableAgent: "No Agent is available. Ask an administrator for access.", reminderCreated: "Hermes reminder created. It will return to this private chat when due.", reminderFailed: "Could not create the Hermes reminder.", reminderReceived: "Received {count} Hermes reminder notification(s).", reminderNotificationTitle: "RelayDesk reminder", reminderNotificationBody: "Hermes has a new reminder result in this chat.",
    runtimeApprovalRequired: "Approval required", runtimeApprovalDetail: "Hermes requests approval", runtimeContextUsage: "Context usage", runtimeRunFailed: "Run failed", runtimeEvent: "Runtime event", runtimeRawEvent: "Runtime raw event", unknown: "unknown",
    newChat: "New chat", expandChatList: "Expand chat list", collapseChatList: "Collapse chat list", noArchivedChats: "No archived chats", restoreAndContinue: "Restore and continue", chatActions: "Chat actions", syncingChat: "Syncing chat", syncChat: "Sync chat", renameChat: "Rename chat", createScheduledTask: "Create scheduled task", archiveChat: "Archive chat", imagesOnly: "Images only", you: "You", operator: "Operator", running: "Running", connectionInterrupted: "Connection interrupted", sending: "Sending", synced: "Synced", thinking: "Thinking…", emptyChatTitle: "Start with a clear goal", emptyChatDescription: "Describe the work. RelayDesk turns the conversation into organized, reusable work.", messageContent: "Message content", restoreBeforeContinue: "Restore this chat before continuing", createChatFirst: "Create a chat first",
    createChatFailed: "Could not create chat. Please try again.", uploadFailed: "Could not upload attachment.", remoteImagesOnly: "This remote Agent supports image attachments only. Documents require RelayDesk to share a directory with Hermes.", fileLoadFailed: "Could not load file contents.", localOperator: "You", runInterrupted: "Runtime was interrupted. Received content has been kept.", sendFailed: "Could not send the message. Your input and attachments were kept; check Hermes and try again.", stopRequested: "Stop requested. Received content will be kept.", stopUnavailable: "This task can no longer be stopped; it may have already finished.", renameFailed: "Could not rename chat. Please try again.", chatRenamed: "Chat name updated.", archiveFailed: "Could not archive chat. Please try again.", chatArchived: "Chat archived.", restoreFailed: "Could not restore chat. Please try again.", chatRestored: "Chat restored.", pinUpdateFailed: "Could not update the pinned state. Please try again.", chatPinned: "Chat pinned.", chatUnpinned: "Chat unpinned.", deleteFailed: "Could not delete chat. Please try again.", chatDeleted: "Chat removed from your RelayDesk list.", toolFailed: "Failed", toolCompleted: "Completed", retrySend: "Send again", imageAttachment: "Image attachment", attachment: "Attachment", attachmentsUnsupported: "This Hermes connection does not support attachments", attachmentForwardUnsupported: "This Hermes connection cannot forward attachments", filePreview: "File preview", download: "Download", closePreview: "Close preview", imagePreview: "Image preview", loadingFile: "Loading file contents…", previewUnavailable: "This file type cannot be previewed in the browser", previewUnavailableDescription: "The file was archived safely. Download it and open it with a local app.", renameChatTitle: "Rename chat", renameChatDescription: "Chat history and related assets will not be affected.", archiveChatTitle: "Archive current chat", archiveChatDescription: "Archive this chat and restore it later from chat history.", confirmArchive: "Archive chat", deleteChatTitle: "Remove chat from RelayDesk", deleteChatDescription: "This chat will be hidden from your RelayDesk list. The Hermes chat and archived assets will not be deleted.", confirmDelete: "Remove chat", reminderTitle: "Create Hermes reminder", reminderDescription: "The completed result returns to this private chat.", closeWindow: "Close dialog", reminderName: "Task name", reminderNamePlaceholder: "For example: Dinner reminder", cronSchedule: "Cron schedule", cronSchedulePlaceholder: "For example: 38 20 * * *", reminderPrompt: "Reminder message", reminderPromptPlaceholder: "For example: Remind me to eat.", creating: "Creating", createTask: "Create reminder",
  },
  "zh-CN": {
    chat: "对话历史", members: "成员授权", settings: "系统设置",
    newConversation: "新建会话", collapse: "折叠侧边栏", expand: "展开侧边栏", logout: "退出登录", administrator: "管理员", member: "成员",
    loginTitle: "进入工作台", loginDescription: "使用已授权的成员账号，开始与 Hermes Agent 协作。", memberName: "成员姓名", memberNamePlaceholder: "例如：王敏", password: "个人密码", passwordPlaceholder: "输入个人密码", signIn: "进入 RelayDesk", verifying: "正在验证", loginFailed: "登录失败，请重试", internalOnly: "仅限公司内网成员使用", firstUse: "首次使用时，工作区密码将创建首位管理员。",
    loginKicker: "团队 AI 工作台", loginHero: "让每一次 Agent 对话，都成为团队的有序工作", loginHeroDescription: "RelayDesk 连接团队成员与 Hermes Agent，将对话、文件与工作成果沉淀为可追溯、可复用的团队资产。",
    connected: "已连接", agentConversation: "与 Hermes Agent 的对话", previewUserInitial: "王", previewUserMessage: "请帮我整理本次需求评审的关键结论和后续行动项。", previewTime: "09:41", previewAgentIntro: "好的，以下是为你整理的要点：", previewPointOne: "确认核心需求范围与优先级", previewPointTwo: "技术方案采用分阶段交付策略", previewPointThree: "新增数据权限校验机制", previewFollowUp: "后续行动项", previewActionOne: "完善 PRD 与流程图", previewActionTwo: "评估接口改造影响", previewComposer: "向 Hermes Agent 发送消息…", agentHealthy: "响应正常，运行良好", viewAgentStatus: "查看 Agent 状态", archivedWork: "归档成果", archiveFileName: "需求评审会议纪要.md", archiveLocation: "团队知识库 / 项目 Alpha", archiveBy: "由 李明 归档于 2026-07-11", archiveDescription: "包含会议结论、行动项与相关讨论记录。", viewDetails: "查看详情", internalWorkspace: "内部团队工作台",
    searchChats: "搜索会话", searchArchivedChats: "搜索归档会话", viewArchive: "查看归档", returnToCurrent: "返回当前会话", archive: "归档", restore: "恢复", rename: "重命名", sync: "同步", syncing: "正在同步", delete: "删除", pin: "置顶", unpin: "取消置顶", currentChat: "当前会话", archivedChat: "已归档会话", createFirstChat: "创建第一个会话", noAuthorizedAgent: "暂无 Agent 授权", messagePlaceholder: "描述你要创作、检查或修改的内容…", sendMessage: "发送消息", addAttachment: "添加附件", stopRun: "停止运行",
    close: "关闭", cancel: "取消", confirm: "确认", save: "保存", name: "名称", systemNotifications: "系统通知", closeNotification: "关闭通知",
    checkingRuntime: "正在检查 Runtime", hermesConnected: "Hermes Agent 已连接", mockConnected: "Mock Runtime 已连接", runtimeDisconnected: "Runtime 未连接",
    syncFailed: "同步失败；本地历史已保留，可稍后重试。", networkInterrupted: "网络连接中断；RelayDesk 本地历史已保留，可稍后重试同步。",
    sessionNotFound: "Hermes 中未找到这个会话；RelayDesk 本地历史已保留。", conversationNotFound: "该会话已无法在 RelayDesk 中使用。", agentAccessRevoked: "你查看该 Agent 历史记录的权限已被撤销。", unauthenticated: "登录已过期，请重新登录后继续。", runtimeUnavailable: "Hermes 暂时不可用；RelayDesk 本地历史已保留，可稍后重试同步。", runtimeAuthFailed: "Hermes 授权已失效，请联系管理员检查 Agent Key。", streamInterrupted: "响应流已中断；已接收内容已保留。", runtimeError: "Hermes 未能完成此请求，请稍后重试。",
    inputRestored: "已恢复上一次输入和附件，确认后可重新发送。", loadingAgents: "正在加载 Agent，请稍候。", noAvailableAgent: "当前没有可使用的 Agent，请联系管理员授权。", reminderCreated: "Hermes 定时任务已创建，到点后将回到这条私聊。", reminderFailed: "创建 Hermes 定时任务失败。", reminderReceived: "收到 {count} 条 Hermes 定时任务提醒。", reminderNotificationTitle: "RelayDesk 定时任务提醒", reminderNotificationBody: "Hermes 有新的定时任务结果，请查看当前会话。",
    runtimeApprovalRequired: "需要批准", runtimeApprovalDetail: "Hermes 请求人工批准", runtimeContextUsage: "上下文用量", runtimeRunFailed: "运行失败", runtimeEvent: "Runtime 事件", runtimeRawEvent: "Runtime 原始事件", unknown: "未知",
    newChat: "新会话", expandChatList: "展开对话列表", collapseChatList: "折叠对话列表", noArchivedChats: "暂无归档会话", restoreAndContinue: "恢复并继续", chatActions: "会话操作", syncingChat: "正在同步会话", syncChat: "同步会话", renameChat: "重命名会话", createScheduledTask: "创建定时任务", archiveChat: "归档会话", imagesOnly: "仅图片附件", you: "你", operator: "操作者", running: "运行中", connectionInterrupted: "连接已中断", sending: "发送中", synced: "已同步", thinking: "正在思考…", emptyChatTitle: "从一个明确的目标开始", emptyChatDescription: "描述需求，RelayDesk 会将整个对话过程沉淀为可管理、可复用的工作成果。", messageContent: "消息内容", restoreBeforeContinue: "请先恢复会话再继续", createChatFirst: "请先创建会话",
    createChatFailed: "新建会话失败，请重试。", uploadFailed: "附件上传失败。", remoteImagesOnly: "当前远程 Agent 仅支持图片附件；文档需要与 RelayDesk 同机或配置共享目录。", fileLoadFailed: "文件内容加载失败。", localOperator: "我", runInterrupted: "运行时中断，已保留已接收内容。", sendFailed: "消息发送失败；已保留输入与附件，请检查 Hermes 状态后重试。", stopRequested: "已请求停止 Runtime 任务，正在保留已接收内容。", stopUnavailable: "当前任务无法停止，可能已经结束。", renameFailed: "重命名会话失败，请稍后重试。", chatRenamed: "会话名称已更新。", archiveFailed: "归档会话失败，请稍后重试。", chatArchived: "会话已归档。", restoreFailed: "恢复会话失败，请稍后重试。", chatRestored: "会话已恢复。", pinUpdateFailed: "更新置顶状态失败，请稍后重试。", chatPinned: "会话已置顶。", chatUnpinned: "已取消置顶。", deleteFailed: "删除会话失败，请稍后重试。", chatDeleted: "会话已从 RelayDesk 列表删除。", toolFailed: "失败", toolCompleted: "已完成", retrySend: "重新发送", imageAttachment: "图片附件", attachment: "附件", attachmentsUnsupported: "当前 Hermes 连接暂不支持附件", attachmentForwardUnsupported: "当前 Hermes 连接暂不支持附件转发", filePreview: "文件预览", download: "下载", closePreview: "关闭预览", imagePreview: "图片预览", loadingFile: "正在加载文件内容…", previewUnavailable: "此文件类型暂不支持浏览器内预览", previewUnavailableDescription: "文件已安全归档，可下载后使用本机应用打开。", renameChatTitle: "重命名会话", renameChatDescription: "会话历史和关联资产不会受到影响。", archiveChatTitle: "归档当前会话", archiveChatDescription: "归档此会话后，仍可在历史记录中恢复。", confirmArchive: "确认归档", deleteChatTitle: "从 RelayDesk 删除会话", deleteChatDescription: "此会话将从你的 RelayDesk 列表隐藏。Hermes 原始会话与已归档资产不会被删除。", confirmDelete: "确认删除", reminderTitle: "创建 Hermes 定时任务", reminderDescription: "完成结果会自动回到当前私聊。", closeWindow: "关闭窗口", reminderName: "任务名称", reminderNamePlaceholder: "例如：晚餐提醒", cronSchedule: "Cron 时间", cronSchedulePlaceholder: "例如：38 20 * * *", reminderPrompt: "提醒内容", reminderPromptPlaceholder: "例如：提醒我去吃饭。", creating: "正在创建", createTask: "创建任务",
  },
} as const;

export type MessageKey = keyof typeof systemMessages.en;

export function t(locale: Locale, key: MessageKey) {
  return systemMessages[locale][key];
}

export const memberMessages = {
  en: {
    access: "Access", memberAccess: "Member access", accessDenied: "Only administrators can view and manage member access.", membersAgents: "Members & Agents", memberAgentAccess: "Member and Agent access", memberAccessDescription: "Members sign in with their own password. Revoking access immediately prevents new chats, uploads, and history access.", memberName: "Member name", initialPassword: "Initial password (8+ characters)", addMember: "Add member", creating: "Creating", working: "Working", disable: "Disable", enable: "Enable", member: "Member", administrator: "Administrator", accountCanSignIn: "Account can sign in", accountDisabled: "Account is disabled", passwordSet: "Personal password set", passwordNotSet: "Password not set", dedicated: "Dedicated", shared: "Shared", saveAccess: "Save Agent access", saving: "Saving", startChats: "Start chats", sendFiles: "Send files", viewHistory: "View history", loadFailed: "Could not load members and Agents.", memberCreated: "Member created. You can now assign Agents.", memberCreateFailed: "Could not create member.", memberNetworkError: "Network error. Check the service connection and try again.", accessSaved: "Agent access saved.", accessSaveFailed: "Could not save access.", accessNetworkError: "Network error. Access was not saved. Please try again.", memberDisabled: "Member disabled.", memberEnabled: "Member enabled.", memberUpdateFailed: "Could not update member.", memberStatusNetworkError: "Network error. Member status was not updated. Please try again.",
  },
  "zh-CN": {
    access: "访问权限", memberAccess: "成员授权", accessDenied: "只有管理员可以查看和修改成员授权。", membersAgents: "成员与 Agent", memberAgentAccess: "成员与 Agent 授权", memberAccessDescription: "员工使用个人密码登录；权限撤销后立即停止新的聊天、上传和历史访问。", memberName: "员工姓名", initialPassword: "初始密码（至少 8 位）", addMember: "新增成员", creating: "正在创建", working: "正在处理", disable: "停用", enable: "启用", member: "成员", administrator: "管理员", accountCanSignIn: "账号可登录", accountDisabled: "账号已停用", passwordSet: "个人密码已设置", passwordNotSet: "等待设置密码", dedicated: "独占", shared: "共享", saveAccess: "保存 Agent 授权", saving: "正在保存", startChats: "发起私聊", sendFiles: "发送文件", viewHistory: "查看历史", loadFailed: "成员与 Agent 数据加载失败。", memberCreated: "成员已创建，请继续分配 Agent。", memberCreateFailed: "成员创建失败", memberNetworkError: "网络异常，成员未创建。请检查服务连接后重试。", accessSaved: "Agent 授权已保存。", accessSaveFailed: "授权保存失败", accessNetworkError: "网络异常，授权未保存。请稍后重试。", memberDisabled: "成员已停用。", memberEnabled: "成员已启用。", memberUpdateFailed: "成员更新失败", memberStatusNetworkError: "网络异常，成员状态未更新。请稍后重试。",
  },
} as const;

export type MemberMessageKey = keyof typeof memberMessages.en;

export function memberT(locale: Locale, key: MemberMessageKey) {
  return memberMessages[locale][key];
}

const runtimeErrorMessageKeys = {
  SESSION_NOT_FOUND: "sessionNotFound",
  CONVERSATION_NOT_FOUND: "conversationNotFound",
  AGENT_ACCESS_REVOKED: "agentAccessRevoked",
  UNAUTHENTICATED: "unauthenticated",
  RUNTIME_UNAVAILABLE: "runtimeUnavailable",
  RUN_TIMEOUT: "runtimeUnavailable",
  RUNTIME_AUTH_FAILED: "runtimeAuthFailed",
  STREAM_INTERRUPTED: "streamInterrupted",
} as const satisfies Record<string, MessageKey>;

export function formatSystemError(locale: Locale, code?: string, fallback?: string) {
  const key = code ? runtimeErrorMessageKeys[code as keyof typeof runtimeErrorMessageKeys] : undefined;
  // Runtime errors may be localized by the host. Do not leak a Chinese fallback
  // into the English UI when RelayDesk cannot map the error code.
  const isChineseFallback = locale === "en" && /[\u4e00-\u9fff]/.test(fallback ?? "");
  return key ? t(locale, key) : !isChineseFallback && fallback ? fallback : t(locale, "runtimeError");
}
