"use client";
import { type FormEvent, useEffect, useState } from "react";
import { Check, Pencil, X } from "lucide-react";
import type { ContentAccount } from "@/modules/contents/service";
import { ConfirmDialog } from "@/shared/components/confirm-dialog";
import { useToast } from "@/shared/components/toast-provider";

type Agent = { id: string; name: string };

export default function AccountsPage() {
  const [items, setItems] = useState<ContentAccount[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [editingId, setEditingId] = useState<string>(); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [pendingDisableId, setPendingDisableId] = useState<string>(); const { notify } = useToast();
  async function load() { const response = await fetch("/api/accounts"); if (response.ok) setItems(await response.json()); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); void fetch("/api/agents").then((response) => response.ok ? response.json() : []).then(setAgents); }, 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const response = await fetch("/api/accounts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: data.get("code"), name: data.get("name"), description: data.get("description"), notes: data.get("notes"), defaultRuntimeConnectionId: data.get("defaultRuntimeConnectionId") || undefined }) }); const result = await response.json(); if (!response.ok) return setError(result.message ?? "账号创建失败"); form.reset(); setError(""); setNotice("内容账号已创建"); await load(); }
  async function update(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await fetch(`/api/accounts/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), description: data.get("description") || null, notes: data.get("notes") || null, defaultRuntimeConnectionId: data.get("defaultRuntimeConnectionId") || null }) }); const result = await response.json(); if (!response.ok) return setError(result.message ?? "账号保存失败"); setItems((current) => current.map((item) => item.id === id ? result : item)); setEditingId(undefined); setNotice("账号设置已保存"); }
  async function disable(id: string) { const response = await fetch(`/api/accounts/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ enabled: false }) }); if (!response.ok) { setError("停用账号失败"); notify("停用账号失败，请稍后重试。", "error"); return; } setItems((current) => current.filter((item) => item.id !== id)); setNotice("账号已停用，历史数据保持不变"); setPendingDisableId(undefined); notify("账号已停用，历史数据保持不变。", "success"); }
  return <section className="standard-page"><p className="eyebrow">账号管理</p><h1>内容账号</h1><p className="muted">维护账号定位、运营备注和默认 Hermes Agent，新私聊会自动继承绑定。</p><form className="account-form" onSubmit={create}><input name="code" placeholder="编号，例如 01" required /><input name="name" placeholder="账号名称" required /><input name="description" placeholder="账号定位（可选）" /><select name="defaultRuntimeConnectionId" defaultValue=""><option value="">不指定默认 Agent</option>{agents.map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><button className="primary-button">新增账号</button><textarea name="notes" placeholder="运营备注（可选）" /></form>{error ? <p className="form-error">{error}</p> : null}{notice ? <p className="content-notice">{notice}</p> : null}<div className="account-grid">{items.map((item) => editingId === item.id ? <form className="account-card-edit" key={item.id} onSubmit={(event) => update(event, item.id)}><header><span>{item.code}</span><div><button type="button" aria-label="取消编辑" onClick={() => setEditingId(undefined)}><X size={15} /></button><button aria-label="保存账号"><Check size={15} /></button></div></header><label>账号名称<input name="name" defaultValue={item.name} required /></label><label>账号定位<textarea name="description" defaultValue={item.description ?? ""} /></label><label>运营备注<textarea name="notes" defaultValue={item.notes ?? ""} /></label><label>默认 Agent<select name="defaultRuntimeConnectionId" defaultValue={item.defaultRuntimeConnectionId ?? ""}><option value="">创建会话时选择</option>{agents.map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label></form> : <article key={item.id}><header><span>{item.code}</span><button aria-label={`编辑 ${item.name}`} onClick={() => setEditingId(item.id)}><Pencil size={15} /></button></header><h2>{item.name}</h2><p>{item.description || "尚未填写账号定位"}</p>{item.notes ? <small>{item.notes}</small> : null}<small>默认 Agent：{agents.find((agent) => agent.id === item.defaultRuntimeConnectionId)?.name ?? "创建会话时选择"}</small><button className="account-disable" onClick={() => setPendingDisableId(item.id)}>停用账号</button></article>)}{!items.length ? <p className="muted">尚未创建内容账号。</p> : null}</div><ConfirmDialog open={Boolean(pendingDisableId)} title="停用内容账号" description="停用后不能再用于新会话，历史会话和内容不会删除。" confirmLabel="确认停用" destructive onConfirm={() => pendingDisableId && void disable(pendingDisableId)} onCancel={() => setPendingDisableId(undefined)} /></section>;
}
